import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">AnimationStart</Link>
        </li>
        <li>
          <Link to="/donesubmit">DoneSubmit</Link>
        </li>
        <li>
          <Link to="/get50">Get50</Link>
        </li>
        <li>
          <Link to="/homescreen">HomeScreen</Link>
        </li>
        <li>
          <Link to="/outsourcingpage">OutsourcingPage</Link>
        </li>
        <li>
          <Link to="/headhuntingpage">HeadHuntingPage</Link>
        </li>
        <li>
          <Link to="/webdevpage">Webdevpage</Link>
        </li>
        <li>
          <Link to="/digitalmarketingpage">DigitalMarketingPage</Link>
        </li>
        <li>
          <Link to="/digitalmarketingservicespage">
            DigitalmarketingServicespage
          </Link>
        </li>
        <li>
          <Link to="/aboutuspage">AboutUspage</Link>
        </li>
        <li>
          <Link to="/contactuspage">ContactUspage</Link>
        </li>
        <li>
          <Link to="/blogpage">Blogpage</Link>
        </li>
        <li>
          <Link to="/blogpostpage">BlogPostpage</Link>
        </li>
        <li>
          <Link to="/blogslistpage">BlogsListpage</Link>
        </li>
        <li>
          <Link to="/desktopone">DesktopOne</Link>
        </li>
        <li>
          <Link to="/desktoptwo">DesktopTwo</Link>
        </li>
        <li>
          <Link to="/desktopthree">DesktopThree</Link>
        </li>
        <li>
          <Link to="/desktopfour">DesktopFour</Link>
        </li>
        <li>
          <Link to="/projectspage">Projectspage</Link>
        </li>
        <li>
          <Link to="/digitalmarketingprojects">Digitalmarketingprojects</Link>
        </li>
        <li>
          <Link to="/webservicespage">WebServicespage</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
